services:
  spark:
    container_name: spark
    hostname: spark
    build: ./spark
    networks:
      - spark-iceberg-minio-network
    ports:
      - 4040:4040
    tty: true
    volumes:
      - ./spark/spark-defaults.conf:/opt/spark-3.5.1-bin-hadoop3/conf/spark-defaults.conf:ro
      - ./data/:/data/:ro
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT=minio:9000
      - AWS_REGION=us-east-1
      - TZ=Asia/Tokyo
    depends_on:
      - s3
  
  s3:
    container_name: s3
    hostname: s3
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    networks:
      - spark-iceberg-minio-network
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - minio-volume:/data/
    tty: true
    ports:
      - 9000:9000
      - 9001:9001
    command: ["server", "/data", "--console-address", ":9001"]
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    networks:
      - spark-iceberg-minio-network
    volumes:
      - db-store:/var/lib/postgresql/data
    tty: true
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hivepassword    

networks:
  spark-iceberg-minio-network:

volumes:
  db-store:
  minio-volume:
